### ISSUE TITLE
Installation error on case-sensitive file systems

### ISSUE THREAD

**Issue by michaelmior** [1rgs/jsonformer#11]
I get the error below when trying to run `poetry install`. This is because the README is listed as `README.md` in `pyproject.toml`, but the file in the repository is named `readme.md` (lowercase). Changing either of these to match solves the problem.

```
$ poetry install
Installing dependencies from lock file

No dependencies to install or update

[Errno 2] No such file or directory: '/home/mmior-admin/apps/jsonformer/README.md'
```

**Comment by 1rgs** [comment]
thanks!
