### ISSUE TITLE
Reduce required Python version (currently v3.10)

### ISSUE THREAD

**Issue by recursionbane** [1rgs/jsonformer#8]
Many standard Ubuntu images ship with Python 3.8.

Can we reduce the required Python version from 3.10 to 3.8?

**Comment by 1rgs** [comment]
thanks! fixed in https://github.com/1rgs/jsonformer/commit/47e69b5cd9da1b95960877b13a55c7322ff28f9c

**Comment by recursionbane** [comment]
Fantastic, thanks!
